name: Compile LaTeX CV

on:
  push:
    paths:
      - 'tex/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk

    - name: Compile CV (Debug Mode)
      working-directory: tex
      run: |
        echo "Files in tex/:"
        ls -l
        echo "Compiling Tushin_CV.tex..."
        latexmk -pdf -interaction=nonstopmode -file-line-error -halt-on-error Tushin_CV.tex
        ls -lh
        cp Tushin_CV.pdf ../files/Tushin_CV.pdf

    - name: Commit and push updated PDF
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add files/Tushin_CV.pdf
        git commit -m "Auto-update CV PDF" || echo "No changes to commit"
        git push

